// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample001.DBContexts;

namespace Sample001.Migrations.SchoolDB
{
    [DbContext(typeof(SchoolDBContext))]
    partial class SchoolDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample001.Models.PositiveCaseModel", b =>
                {
                    b.Property<string>("pubDate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("patientNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pubDate");

                    b.ToTable("Covid19Results");
                });

            modelBuilder.Entity("Sample001.Models.Prefs.FukuiModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("developDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientSymptom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prefCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prefName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pubDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recoverOrNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("travelRecord")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FukuiResults");
                });

            modelBuilder.Entity("Sample001.Models.Prefs.GunmaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pubDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("GunmaResults");
                });

            modelBuilder.Entity("Sample001.Models.Prefs.KanagawaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("patientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pubDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("KanagawaResults");
                });
#pragma warning restore 612, 618
        }
    }
}
